asciidoctor:
  attributes:
    source-highlighter: highlightjs
    sectanchors: ''
    icons: font
    outfilesuffix: ''
    add-copy-button-to-env-var: true
    source_adoc_base_dir : /home/ynojima/workspace/ja.quarkus.io/build/jekyll-source/ #TODO
    po_base_dir : /home/ynojima/workspace/ja.quarkus.io/l10n/po/ja_JP/ #TODO
